name: CI/CD - Build, Push, and Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: CI pipeline
    runs-on: self-hosted

    steps:
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/react-apache-app:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/react-apache-app:latest

  deploy:
    name: CD pipeline
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull Latest Docker Image and Deploy
        run: |
          docker stop react-apache-container || true
          docker rm react-apache-container || true
          docker image prune -a -f
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/react-apache-app:latest
          docker run -d -p 80:80 --name react-apache-container ${{ secrets.DOCKERHUB_USERNAME }}/react-apache-app
